# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: centos:7.3.1611 # Current CentOS version on Farux (IRSN farm)
    steps:
      - checkout # Retrieve the latest revision
      - run:
          name: Version5 compilation
          command: |
            echo 'Hello World!'
            yum -y install gcc-gfortran make
            gfortran --version
            make --version
            cd Drakkar/Version5/Donjon/src
            make
